version: "3.8"
services:

  frontend:
    build:
      context: .
    environment:
      NODE_ENV: ci
      AWS_ACCESS_KEY_ID: example
      AWS_SECRET_ACCESS_KEY: example
      AWS_DEFAULT_REGION: eu-west-2
      AWS_ENDPOINT_URL: http://localstack:4566
    ports:
      - "8085:5000"

  redis:
    image: redis:6.0.9
    restart: on-failure
    ports:
      - "6379:6379"

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:3.1
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      DEBUG: ${DEBUG:-0}
      AWS_DEFAULT_REGION: eu-west-2
      SERVICES: sqs, s3
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack_bootstrap:/etc/localstack/init/ready.d/"

  request-api:
    image: public.ecr.aws/l6z6v3j6/development-pub-async-request-api:main
    # image: request-api:latest # Uncomment when working locally with this file
    environment:
      PYTHONUNBUFFERED: 1
      AWS_ENDPOINT_URL: http://localstack:4566
      CELERY_BROKER_URL: sqs://ABCDEFGHIJKLMNOPQRST:ZYXK7NiynGlTogH8Nj+P9nlE73sq3@localstack:4566
      AWS_DEFAULT_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: example
      AWS_SECRET_ACCESS_KEY: example
      SQS_QUEUE_NAME: request-queue
      DATABASE_URL: postgresql://postgres:password@request-db/request_database
    restart: on-failure
    ports:
      - "8000:8000"

  request-db:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: request_database
    restart: on-failure

  request-processor:
    image: public.ecr.aws/l6z6v3j6/development-pub-async-request-processor:main
    # image: request-processor:latest # Uncomment when working locally with this file
    environment:
      PYTHONUNBUFFERED: 1
      AWS_ENDPOINT_URL: http://localstack:4566
      AWS_DEFAULT_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: example
      AWS_SECRET_ACCESS_KEY: example
      # CELERY_BROKER_URL: sqs://@sqs.eu-west-2.amazonaws.com
      CELERY_BROKER_URL: sqs://example:example@localstack:4566
      CELERY_BROKER_REGION: eu-west-2
      CELERY_BROKER_IS_SECURE: "false"
      DATABASE_URL: postgresql://postgres:password@request-db/request_database
      REQUEST_FILES_BUCKET_NAME: dluhc-data-platform-request-files-local
    restart: on-failure
    deploy:
      replicas: 2
    volumes:
      - "./request-processor-celery/docker_volume:/opt"

