asyncRequestApi: {
    url: http://development-pub-async-api-lb-69142969.eu-west-2.elb.amazonaws.com
}
aws: {
    region: eu-west-2,
    bucket: 'development-pub-async-request-files',
}
redis: {
    secure: true,
    host: 'development-pub-async-redis-3dqynz.serverless.euw2.cache.amazonaws.com',
    port: '6379'
}
url: 'https://publish.development.digital-land.info/'
