asyncRequestApi: {
    url: http://development-pub-async-api-lb-69142969.eu-west-2.elb.amazonaws.com
}
aws: {
    region: eu-west-2,
    bucket: 'development-pub-async-request-files',
}
datasetteUrl: https://datasette.development.planning.data.gov.uk
downloadUrl: 'https://download.development.planning.data.gov.uk' 
redis: {
    secure: true,
    host: 'development-pub-async-redis-3dqynz.serverless.euw2.cache.amazonaws.com',
    port: 6379
}
url: 'https://provide.development.planning.data.gov.uk/'
features:
  submitEndpointForm:
    enabled: true
  provisionBasedDatasets:
    # This feature will load datasets based on provisionReasons
    enabled: true
  nonAuthPages:
    # This feature enables pages to show non-authoritative datasets
    # If off, it will still check for local-plan datasets.
    enabled: true
