asyncRequestApi: {
    url: http://localhost:8001,
    port: 8001
}
aws: {
    region: eu-west-2,
    bucket: 'dluhc-data-platform-request-files-local',
    endpoint: 'http://localhost:4566',
    s3ForcePathStyle: true,
}